app:
  telegram-token: "6918381858:AAEXd5FklSbMO8cu-4Rhw9V3oYbHuIQCfGM"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
